### PR TITLE
Add options for tray icon behavior

### PR DESCRIPTION
**Pull request by ckaczor**
I'm used to slightly different behavior for applications with a tray icon:

1. Hiding when the window is minimized rather than when it is closed
1. Showing window with a double click on the tray icon rather than a single click

I added some options to allow this but preserving the current defaults:

- "Hide main window when minimized" - defaults to off
- "Hide main window when closed" - defaults to on
- "Mouse trigger" - default to single click - has option for double click
- "Mouse action" - defaults to "toggle window visibility" - has option for "show window"

The mouse options (trigger/action) are hidden on Linux since there's no double click for the tray icon.

I tested on Windows and Linux but don't have a Mac system to test on.

Thanks!

### CODE REVIEW

**Comment by Thomas101** [comment]
Hi, thanks @ckaczor and apologies for being tardy on merging this into WMail. It's been a hectic few weeks. I've merged this in now and added a few checks for different operating systems. macOS & linux don't quite match the same level support as windows with the tray.

Also related commits: ce9d23c19d093835f0e56f83047b821e75c2f7fe dedadcf3621c5c99e59a2ce6c1db06021652a518

If you have a chance would you mind reaching out to me using the [wavebox contact form](https://wavebox.io/contact)? Thanks!

**Comment by ckaczor** [comment]
I notice in the latest beta builds that the hide when closed/minimized options are gone. I really liked being able to hide on minimize and close - are they coming back? Do I need to update for the current code and issue a new pull request?

Thanks!

**Comment by Thomas101** [comment]
Hi,

The behaviour has changed slightly in this release, I thought we managed to capture most of the cases but on second look I think we might have missed one...

* "Hide main window when minimized" - *This setting has gone without a replacement*
* "Hide main window when closed" - always set to on, however, if the app is pinned to the taskbar the app will minimize to the taskbar rather than hide
* "Mouse trigger" - Replaced by `Tray Mouse Actions` under settings
* "Mouse action" - Replaced by `Tray Mouse Actions` under settings

What's the setting/behaviour that you're looking for? It is being able to hide the app when pressing minimize?

**Comment by ckaczor** [comment]
Yeah - the only thing I'm missing is the ability to hide on minimize. The mouse action settings didn't upgrade but I was able to reset them to how I wanted.

**Comment by Thomas101** [comment]
Okay, I'll have a look if I can add this back in to the next release

**Comment by Thomas101** [comment]
I've re-added the behaviour in under https://github.com/wavebox/waveboxapp/commit/4ecb7912e4ac6bd69d5c9a1db3e7db94f93219f1 https://github.com/wavebox/waveboxapp/commit/ef1bd343506454993f747c9a07862d9cb75185b7 https://github.com/wavebox/waveboxapp/commit/b9fb2b5f03283df8f5671be13519ee88354b2cd2

It's under a separate option now though, so you'll need to re-configure it as you want it. Should be out in a release shortly :)

**Comment by ckaczor** [comment]
Thanks - looking forward to it. =)

**Comment by Thomas101** [comment]
3.12.0 has just gone out which includes this. The setting won't be carried across from your previous config though.

screen shot 2018-03-22 at 08 49 04

**Comment by ckaczor** [comment]
Works great - thanks again. =)

**Pull request merged**
